apiVersion: apps/v1
kind: Deployment
metadata:
  name: greeter-client-round-robin-envoy
  labels:
    app: greeter_client_envoy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: greeter_client_envoy
  template:
    metadata:
      labels:
        app: greeter_client_envoy
    spec:
      containers:
      - name: greeter-client-round-robin
        image: rchughtai/grpc:client
        imagePullPolicy: Never
        env:
        - name: GREETER_SERVICE_TARGET
          value: "localhost:10000"
        - name: GREETER_LB_POLICY_NAME
          value: "round_robin"
      - name: envoy-sidecar
        image: envoy-static:latest
        imagePullPolicy: Never




